debug: false

web:
  port: 8182

#telegram:
#  token: "INSERTYOUR:TOKEN"
#  chat: INSERTYOURCHATID

#gotify:
#  server: "http://yourserver:port"
#  token: INSERTYOURTOKEN

mqtt:
  server: openwrt.lan
  port: 1883
#  user: mqttusername
#  password: mqttpassword
  topic: 
   - "/sensors/#"
   - "/stats/#"

history: 10

ping:
  - name: host1
    address: host1.lan
  - name: host2
    address: host2.lan

pinginterval: 60
