debug: false

#web:
#  port: 8080

#telegram:
#  token: "INSERTYOUR:TOKEN"
#  chat: INSERTYOURCHATID

#gotify:
#  server: "http://yourserver:port"
#  token: INSERTYOURTOKEN

mqtt:
  server: openwrt.lan
  port: 1883
#  user: mqttusername
#  password: mqttpassword
  topic: 
   - "/sensors/#"
   - "/stats/#"

mqtthistory: 10

ping:
  - name: openwrt.lan
    address: openwrt.lan

pinginterval: 60

http:
  - name: google
    address: http://google.com
#    value: google

httpinterval: 60
httptimeout: 5000
